apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: k8s-as-backend-webhook-server
  name: k8s-as-backend-webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: k8s-as-backend-webhook-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: k8s-as-backend-webhook-server
    spec:
      containers:
      - image: crixo/k8s-as-backend-webhook-server:v.0.0.0
        name: k8s-as-backend-webhook-server
        args:
          - -tls-cert-file=/etc/webhook/certs/cert.pem
          - -tls-private-key-file=/etc/webhook/certs/key.pem
          - -v=2
        env:
          - name: TODO_APP_SVC
            value: http://todo-app-svc:5000
        volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-example-certs
