apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: k8s-as-backend-webhook-server
  name: admission-webhook-example-svc
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    run: k8s-as-backend-webhook-server
status:
  loadBalancer: {}
